# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wnagzihxa1n's Blog
email: wnagzihxa1n@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<br>Welcome to wnagzihxa1n's Blog"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wnagzihxa1n.vip" # the base hostname & protocol for your site
twitter_username: wnagzihxa1n
github_username:  wnagzihxa1n

# Build settings
markdown: kramdown
