# Site settings
title: wnagzihxa1n's Blog
email: wnagzihxa1n@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wnagzihxa1n.vip" # the base hostname & protocol for your site
twitter_username: wnagzihxa1n
github_username:  wnagzihxa1n
flickr_url: ""
disqus_shortname: wnagzihxa1n

imageurl: ""

# Build settings
markdown: kramdown
kramdown:
        input: GFM
        hard_wrap: true
        syntax_highlighter_opts:
                disable: true
# _pages
include: ['_pages']