# Site settings
title:          wnagzihxa1n's Blog
description:    "应用侧漏洞与CTF题解：https://wnagzihxa1n.gitbook.io"
url:            https://wnagzihxa1n.vip

# Author
author:
  name:         Wang Zhixian(@wnagzihxa1n)
  email:        wnagzihxa1n@gmail.com
  url:          https://wnagzihxa1n.vip

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       1000

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: wnagzihxa1n@gmail.com
  github: https://github.com/wnagzihxa1n
